<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="8.0.0" />
    <PackageVersion Include="FluentAssertions" Version="[7.2.1]" />
    <PackageVersion Include="GitHub.Migration" Version="1.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Octoshift" Version="1.27.0" />
    <PackageVersion Include="Octoshift.Extensions" Version="1.0.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>
</Project>
